export default {
  greeting: 'مرحبا',
  logo: 'الصحه',
  OwnNotFound: 'صفحة غير موجودة',
  home: 'الرئيسية',
  contactUs: 'اتصل بنا',
  articles: 'مقالات',
  blogs: 'المدونات',
  aboutUs: 'معلومات عنا',
  profile: 'الملف الشخصي',
  Footer: 'تذييل',
  username: 'اسم المستخدم',
  email: 'البريد الالكتروني',
  password: 'كلمة المرور',
  requiredName: 'الرجاء ادخال اسمك',
  requiredEmail: 'الرجاء ادخال البريد الالكتروني',
  requiredAge: 'الرجاء ادخال العمر',
  requiredGender: 'الرجاء ادخال جنس',
  requiredPhone: 'الرجاء ادخال رقم الهاتف',
  requiredPassword: 'الرجاء ادخال كلمة المرور',
  requiredHeight: 'الرجاء ادخال الطول',
  requiredWeight: 'الرجاء ادخال الوزن',
  requiredConfirmPassword: 'الرجاء تأكيد كلمة المرور',
  requiredUpload: 'الرجاء تحميل صورة',
  requiredCardNumber: 'الرجاء ادخال رقم البطاقة',
  requiredCategory: 'الرجاء اختيار الرياضيه',
  requiredMessage: 'الرجاء ادخال الرسالة',
  LogIn: 'تسجيل الدخول',
  successLog: 'تم تسجيل الدخول بنجاح',
  errorLog: 'خطأ في تسجيل الدخول',
  LogOutMessage: 'تم تسجيل الخروج بنجاح',
  LogOut: 'تسجيل الخروج',
  Language: 'اللغة',
  onError:
    'الرجاء إدخال البريد الإلكتروني الصحيح وكلمة المرور. لاحظ أن كلا الحقلين قد يكونا حساسين لحالة الأحرف.',
  logInTitle: 'تسجيل الدخول إلى تطبيق ',
  forget: 'هل نسيت كلمة المرور؟',
  click: 'اضغط هنا',
  sinUp: 'تسجيل',
  sinUpTitle: 'ليس لديك حساب؟',
  phone: 'هل نسيت كلمة المرور؟',
  ButForget: 'ارسال كود التفعيل',
  desForgot:
    'ادخل رقم هاتفك وسوف تتلقى كود التفعيل. لاحظ أن كلا الحقلين قد يكونا حساسين لحالة الأحرف.',
  sin: 'هل لديك حساب؟ ',
  for: ' نسيت كلمة المرور',
  senUpMes: 'تسجيل حساب  ',
  contactTitle: 'اتصل بنا',
  contactDesc: 'نقوم بالاستقبال على استفساراتك والدعم 24/7.',
  contactName: 'الاسم',
  contactEmail: 'البريد الالكتروني',
  contactMessage: 'الرسالة',
  contactSubmit: 'ارسال',
  profileTitle: 'اكمل ملفك الشخصي',
  profileDesc: 'يمكنك تعديل معلوماتك الشخصية',
  uploadImage: 'تحميل صورة',
  name: 'الاسم',
  age: 'العمر',
  gender: 'الجنس',
  male: 'ذكر',
  female: 'أنثى',
  weight: 'الوزن',
  height: 'الطول',
  sports: 'اختيار الرياضيه التي تمارسها',
  save: 'حفظ',
  swimming: 'سباحة',
  running: 'الجري',
  football: 'كرة القدم',
  basketball: 'كرة السلة',
  gym: 'الصالة الرياضية',
  tennis: 'تنس',
};


