export default {
  greeting: 'مرحبا',
  logo:"الصحه", 
  OwnNotFound: 'صفحة غير موجودة',
  product: 'المنتجات',
  cart: 'عربة التسوق',
  home : 'الرئيسية',
  Footer: 'تذييل',
  requiredName: 'الرجاء ادخال اسمك',
  requiredEmail: 'الرجاء ادخال البريد الالكتروني',
  requiredPhone: 'الرجاء ادخال رقم الهاتف',
  requiredPassword: 'الرجاء ادخال كلمة المرور',
  requiredConfirmPassword: 'الرجاء تأكيد كلمة المرور',
  requiredCode: 'الرجاء ادخال كود التفعيل',
  requiredAddress: 'الرجاء ادخال العنوان',
  requiredCity: 'الرجاء ادخال المدينة',
  requiredCountry: 'الرجاء ادخال الدولة',
  requiredZip: 'الرجاء ادخال الرمز البريدي',
  requiredState: 'الرجاء ادخال الولاية',
  requiredCardNumber: 'الرجاء ادخال رقم البطاقة',
  requiredCvv: 'الرجاء ادخال رقم البطاقة',
  requiredExpiry: 'الرجاء ادخال تاريخ الانتهاء',
  LogIn: 'تسجيل الدخول',
  successLog: 'تم تسجيل الدخول بنجاح',
  errorLog: 'خطأ في تسجيل الدخول',
  LogOutMessage: 'تم تسجيل الخروج بنجاح',
  LogOut: 'تسجيل الخروج',
  Language: 'اللغة',
};


