export default {
  greeting: 'Hello',
  logo:"Health",
  OwnNotFound: 'OwnNotFound',
  product: 'Products',
  cart: 'Cart',
  home : 'Home',
  Footer: 'Footer',
  requiredName: 'Please input your username!',
  requiredEmail: 'Please input your email!',
  requiredPhone: 'Please input your phone!',
  requiredPassword: 'Please input your password!',
  requiredConfirmPassword: 'Please confirm your password!',
  requiredCode: 'Please input your code!',
  requiredAddress: 'Please input your address!',
  requiredCity: 'Please input your city!',
  requiredCountry: 'Please input your country!',
  requiredZip: 'Please input your zip!',
  requiredState: 'Please input your state!',
  requiredCardNumber: 'Please input your card number!',
  requiredCvv: 'Please input your cvv!',
  requiredExpiry: 'Please input your expiry!',
  LogIn: 'LogIn',
  successLog: 'Success LogIn',
  errorLog: 'Error LogIn',
  LogOutMessage: 'LogOut successfully',
  LogOut: 'LogOut',
  Language: 'Language',
};
