export default {
  greeting: 'Hello',
  logo: 'Health',
  OwnNotFound: 'Go Back To The Homepage',
  product: 'Products',
  cart: 'Cart',
  homeTab: 'Home',
  profileTab: 'Profile',
  contactUs: 'Contact Us',
  articles: 'Articles',
  blogs: 'Blogs',
  aboutUs: 'About Us',
  profile: 'Profile',
  calories: 'Calories',
  services: 'Services',
  footer: 'Footer',
  username: 'username',
  email: 'email',
  password: 'password',
  requiredName: 'Please input your username!',
  requiredAge: 'Please input your age!',
  requiredUpload: 'Please upload your image!',
  requiredGender: 'Please input your gender!',
  requiredEmail: 'Please input your email!',
  requiredPhone: 'Please input your phone!',
  requiredWeight: 'Please input your weight!',
  requiredPassword: 'Please input your password!',
  requiredHeight: 'Please input your height!',
  requiredConfirmPassword: 'Please confirm your password!',
  requiredCardNumber: 'Please input your card number!',
  requiredMessage: 'Please input your message!',
  requiredCategory: 'Please select a sports!',
  requiredBurn: 'Please Select your burn rate!',
  requiredExercise: 'Please Select your exercise rate!',
  requiredGoal: 'Please Select your goal!',
  LogIn: 'LogIn',
  successLog: 'Success LogIn',
  errorLog: 'Error LogIn',
  LogOutMessage: 'LogOut successfully',
  LogOut: 'LogOut',
  Language: 'Language',
  onError:
    'Please enter a valid email and password. Make sure your fields are not case-sensitive.',
  logInTitle: 'Login to ',
  forget: 'Forget password ?',
  click: 'Click here',
  sinUp: 'Sign up',
  sinUpTitle: 'Don’t have an account ?',
  phone: 'Forget password ?',
  ButForget: 'Send Verification Code',
  desForgot:
    'Enter your account Phone to reset the password. Then you will want to receive a verification code. If you have any problem about password reset plase',
  sin: 'Do you have an account ? ',
  for: 'Forget',
  senUpMes: 'Sign up to ',
  contactTitle: 'Contact Health',
  contactDesc:
    'Our team receives your inquiries and provides support 24/7.',
  contactName: 'Name',
  contactEmail: 'Email',
  contactMessage: 'Message',
  contactSubmit: 'Submit',
  profileTitle: 'complete your profile',
  profileDesc: 'You can edit your personal information',
  uploadImage: 'Upload Image',
  name: 'Name',
  age: 'Age',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  weight: 'Weight',
  height: 'Height',
  sports: 'Select Sports that you practice',
  save: 'Save',
  swimming: 'Swimming',
  running: 'Running',
  football: 'Football',
  basketball: 'Basketball',
  gym: 'Gym',
  tennis: 'Tennis',
  caloriesTitle: 'Calculate The Calories',
  burn: 'Burn rate',
  burn1: 'weak burn',
  burn2: 'Medium burn',
  burn3: 'High burn',
  exercise: 'how many days of exercise',
  days: 'Days',
  calculate: 'Calculate',
  carbs: 'Carbs',
  protein: 'Protein',
  fat: 'Fat',
  totalCalories: 'Total Calories',
  caloriesMore: 'calories more than',
  caloriesLess: 'calories less than',
  bodyShape: 'Body shape',
  skinny: 'Slim ',
  normal: 'normal weight',
  overweight: 'Overweight',
  firstDegree: 'First degree Obesity',
  secondDegree: 'Second degree Obesity',
  dangerousObesity: 'Dangerous Obesity',
  des1: "1. Malnutrition: Lack of proper nutrition leading to weight loss and other health issues.2. Hyperthyroidism: Overactive thyroid gland can cause weight loss and thinning.3. Celiac disease: Autoimmune disorder affecting the small intestine's ability to absorb nutrients, leading to weight loss.4. Cancer: Some types of cancer can cause weight loss and muscle wasting.5. Eating disorders: Conditions like anorexia nervosa or bulimia can result in severe weight loss.It's important to note that being thin does not automatically mean someone has a disease, but it can be a sign to investigate further if there are concerns about a person's health.",
  des2: "Reaching a normal weight is important for maintaining overall health and preventing obesity or underweight diseases. Maintaining a normal weight requires a healthy balance between physical activity and proper nutrition. In the above context, 'normal weight' refers to a normal weight that is ideal for health and fitness.",
  des3: " The case when the weight is excessed or above the usual or ideal level. In the context presented, 'overweight' is used to refer to the phenomenon of overweight that a person faces and is considered a health challenge. This word reflects a situation that must be faced and taken seriously, whether through lifestyle changes or a healthy diet.",
  des4: 'First degree Obesity is considered a moderate level of obesity and may be associated with an increased risk of various health conditions such as heart disease, diabetes, and hypertension. It is important for individuals in this category to consult with healthcare professionals for guidance on managing their weight and reducing associated health risks.',
  des5: 'Second degree Obesity is considered a severe level of obesity and is associated with a significantly increased risk of various health conditions such as cardiovascular disease, type 2 diabetes, sleep apnea, and joint problems. Individuals in this category are advised to seek medical advice and support for weight management to reduce health risks and improve overall well-being.',
  des6: 'Serious obesity is a serious health condition caused by excessive weight gain, and is considered a serious health problem that may lead to serious health complications. A person with dangerous obesity is characterized by the accumulation of excess fat in the body and an increased risk of chronic diseases such as heart disease, diabetes, and high blood pressure. Rapid intervention, a healthy diet and exercise are recommended to avoid serious health problems associated with obesity.',
  foodCalories: 'Calories For Food',
  selectFood: 'Select Food',
  LogOutMessageModal: 'Are you sure you want to log out?',
  okText: 'Ok',
  cancelText: 'Cancel',
  websiteName: 'Sihtk Bilamsa',
  homePage: {
    hero: {
      h1_1: 'Build a perfect',
      h1_2: 'Health growth',
      p: 'A no brainer solution to achieving your dream physique and optimizing your health',
      btn: 'Join us now !'
    }
  },
  aboutPage: {
    about: 'About',
    aboutDescriptionP1:
      'We aim to provide a comprehensive platform to promote health and well-being, striving to assist you in improving your healthy lifestyle. We offer a range of tools and features to help you track your physical activity and set healthy goals.',
    aboutDescriptionP2:
      'Additionally, we endeavor to provide important data and statistics to help you monitor your progress and make better health decisions. Furthermore, we offer articles and educational resources on health to assist you in making informed and healthy choices.',
    teamSectionTitlePart1: 'Meet Our',
    teamSectionTitlePart2: 'Team'
  },
  popupCanceledMessage: 'Thank you for choosing to stay with us',

  goal:"Goal",
  moreCal:" gain weight",
  lessCal:" lose weight",
  stability:"Weight stability",
  }
