export default {
  greeting: 'Hello',
  logo: 'Health',
  OwnNotFound: 'OwnNotFound',
  product: 'Products',
  cart: 'Cart',
  home: 'Home',
  contactUs: 'Contact Us',
  articles: 'Articles',
  blogs: 'Blogs',
  aboutUs: 'About Us',
  profile: 'Profile',
  calories: 'Calories',
  services: 'Services',
  Footer: 'Footer',
  username: 'username',
  email: 'email',
  password: 'password',
  requiredName: 'Please input your username!',
  requiredAge: 'Please input your age!',
  requiredUpload: 'Please upload your image!',
  requiredGender: 'Please input your gender!',
  requiredEmail: 'Please input your email!',
  requiredPhone: 'Please input your phone!',
  requiredWeight: 'Please input your weight!',
  requiredPassword: 'Please input your password!',
  requiredHeight: 'Please input your height!',
  requiredConfirmPassword: 'Please confirm your password!',
  requiredCardNumber: 'Please input your card number!',
  requiredMessage: 'Please input your message!',
  requiredCategory: 'Please select a sports!',
  requiredBurn: 'Please Select your burn rate!',
  requiredExercise: 'Please Select your exercise rate!',
  LogIn: 'LogIn',
  successLog: 'Success LogIn',
  errorLog: 'Error LogIn',
  LogOutMessage: 'LogOut successfully',
  LogOut: 'LogOut',
  Language: 'Language',
  onError:
    'Please enter a valid email and password. Make sure your fields are not case-sensitive.',
  logInTitle: 'Login to ',
  forget: 'Forget password ?',
  click: 'Click here',
  sinUp: 'Sign up',
  sinUpTitle: 'Don’t have an account ?',
  phone: 'Forget password ?',
  ButForget: 'Send Verification Code',
  desForgot:
    'Enter your account Phone to reset the password. Then you will want to receive a verification code. If you have any problem about password reset plase',
  sin: 'Do you have an account ? ',
  for: 'Forget',
  senUpMes: 'Sign up to ',
  contactTitle: 'Contact Health',
  contactDesc:
    'Our team receives your inquiries and provides support 24/7.',
  contactName: 'Name',
  contactEmail: 'Email',
  contactMessage: 'Message',
  contactSubmit: 'Submit',
  profileTitle: 'complete your profile',
  profileDesc: 'You can edit your personal information',
  uploadImage: 'Upload Image',
  name: 'Name',
  age: 'Age',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  weight: 'Weight',
  height: 'Height',
  sports: 'Select Sports that you practice',
  save: 'Save',
  swimming: 'Swimming',
  running: 'Running',
  football: 'Football',
  basketball: 'Basketball',
  gym: 'Gym',
  tennis: 'Tennis',
  caloriesTitle: 'Calculate The Calories',
  burn: 'Burn rate',
  burn1: 'weak burn',
  burn2: 'Medium burn',
  burn3: 'High burn',
  exercise: 'how many days of exercise',
  days: 'Days',
  calculate: 'Calculate',
  carbs: 'Carbs',
  protein: 'Protein',
  fat: 'Fat',
  totalCalories: 'Total Calories',
  caloriesMore: 'calories more than',
  caloriesLess: 'calories less than',
  websiteName: 'Sihtk Bilamsa',
  aboutPage: {
    about: 'About',
    aboutDescriptionP1:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore a illo, deserunt illum at similique soluta. Deleniti eligendi sunt, inventore eius, quod culpa architecto quibusdam, vitae consequatur harum odit nulla!',
    aboutDescriptionP2:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore a illo, deserunt illum at similique soluta. Deleniti eligendi sunt, inventore eius, quod culpa architecto quibusdam, vitae consequatur harum odit nulla!'
  }
};
